build_linux:
  stage: build
  image: electronuserland/builder:latest
  script:
    - "echo GIT_BRANCH=\"$CI_COMMIT_REF_NAME\" > electron-builder.env"
    - "npm install --no-audit"
    - "npm run build-native-linux"
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-linux"
    paths:
      - dist-native/*.tar.gz
      - dist-native/*.AppImage
      - dist-native/*.deb

build_win:
  stage: build
  image: electronuserland/builder:wine
  script:
    - "echo GIT_BRANCH=\"$CI_COMMIT_REF_NAME\" > electron-builder.env"
    - "npm install --no-audit"
    - "npm run build-native-win"
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-win"
    paths:
      - dist-native/*.exe
      - dist-native/*.zip

build_mac:
  stage: build
  image: blocknetdx/devbuilds:blockdx-gitlab-mac
  script:
    - "echo GIT_BRANCH=\"$CI_COMMIT_REF_NAME\" > electron-builder.env"
    - "npm install --no-audit"
    - "npm run build-native-mac"
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-mac"
    paths:
      - dist-native/mac/BLOCK DX.app

test_artifacts:
  stage: test
  image: ubuntu:bionic
  script:
    - "set -- dist-native/BLOCK-DX-*-linux.tar.gz && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-linux.AppImage && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-linux.deb && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-win.exe && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-win-x64.zip && [[ -f \"$1\" ]]"
    - "set -- dist-native/mac/BLOCK*DX.app && [[ -d \"$1\" ]]"
