module.exports = {
  SELECT_SETUP_TYPE: 'SELECT_SETUP_TYPE',
  SELECT_WALLET_VERSIONS: 'SELECT_WALLET_VERSIONS',
  CONFIGURATION_COMPLETE: 'CONFIGURATION_COMPLETE',
  SELECT_WALLETS: 'SELECT_WALLETS',
  EXPERT_SELECT_WALLET_VERSIONS: 'EXPERT_SELECT_WALLET_VERSIONS',
  SELECT_WALLET_DIRECTORIES: 'SELECT_WALLET_DIRECTORIES',
  EXPERT_SELECT_SETUP_TYPE: 'EXPERT_SELECT_WALLET_TYPE',
  FINISH: 'FINISH',
  ENTER_BLOCKNET_CREDENTIALS: 'ENTER_BLOCKNET_CREDENTIALS',
  ENTER_WALLET_CREDENTIALS: 'ENTER_WALLET_CREDENTIALS',
  CONFIGURATION_MENU: 'CONFIGURATION_MENU'
};
