module.exports = {
  CONFIGURATION_SETUP: 'CONFIGURATION SETUP',
  RPC_SETTINGS: 'RPC SETTINGS',
  FRESH_SETUP: 'FRESH SETUP',
  FRESH_SETUP_QUICK_CONFIGURATION: 'FRESH SETUP - QUICK CONFIGURATION SETUP',
  FRESH_SETUP_EXPERT_CONFIGURATION: 'FRESH SETUP - EXPERT CONFIGURATION SETUP',
  ADD_WALLET: 'ADD WALLET',
  ADD_WALLET_QUICK_CONFIGURATION: 'ADD WALLET - QUICK CONFIGURATION SETUP',
  ADD_WALLET_EXPERT_CONFIGURATION: 'ADD WALLET - EXPERT CONFIGURATION SETUP',
  UPDATE_WALLET: 'UPDATE WALLET',
  UPDATE_WALLET_QUICK_CONFIGURATION: 'UPDATE WALLET - QUICK CONFIGURATION SETUP',
  UPDATE_WALLET_EXPERT_CONFIGURATION: 'UPDATE WALLET - EXPERT CONFIGURATION SETUP',
};
